const $=id=>document.getElementById(id);
function getCart(){return JSON.parse(localStorage.getItem("ay_cart")||"[]")}
function setCart(c){localStorage.setItem("ay_cart",JSON.stringify(c));updateCounts()}
function getWish(){return JSON.parse(localStorage.getItem("ay_wish")||"[]")}
function setWish(w){localStorage.setItem("ay_wish",JSON.stringify(w));updateCounts()}
function money(n){return "₹"+Number(n).toLocaleString("en-IN")}
function updateCounts(){let c=getCart(),w=getWish();let ce=$("cartCount"),we=$("wishCount");if(ce)ce.textContent=c.reduce((a,x)=>a+x.qty,0);if(we)we.textContent=w.length}
function nav(){if(!$("navbar"))return;$("navbar").innerHTML=`<nav><a class="logo" href="index.html">ayu<span>shtha</span><small>HERBAL TEA</small></a><div class="navlinks"><a href="index.html">Home</a><a href="shop.html">Shop</a><a href="about.html">About</a><a href="contact.html">Contact</a><a href="faq.html">FAQ</a></div><div class="navicons"><a href="login.html">👤</a><a href="wishlist.html">♡ <b id="wishCount">0</b></a><a href="cart.html">🛒 <b id="cartCount">0</b></a></div><button class="menu" onclick="document.querySelector('.navlinks').classList.toggle('show')">☰</button></nav>`;updateCounts()}
function foot(){if(!$("footer"))return;$("footer").innerHTML=`<footer><div><a class="logo" href="index.html">ayu<span>shtha</span><small>HERBAL TEA</small></a><p>Nature's goodness in every sip.</p></div><div><h4>Shop</h4><a href="shop.html">All Teas</a><a href="shop.html?cat=Detox">Detox</a><a href="shop.html?cat=Relaxation">Relaxation</a><a href="shop.html?cat=Immunity">Immunity</a></div><div><h4>Help</h4><a href="contact.html">Contact</a><a href="faq.html">FAQ</a><a href="orders.html">Orders</a></div><div><h4>Follow</h4><p>Instagram • Facebook • YouTube</p></div><div class="copyright">© 2026 Ayushtha. Frontend demo.</div></footer>`}
function card(p){let wish=getWish().includes(p.id);return `<article class="product-card"><div class="product-art">${p.emoji}<button class="heart ${wish?'active':''}" onclick="toggleWish(${p.id})">${wish?'♥':'♡'}</button></div><div class="product-info"><span class="tag">${p.category}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="rating">★ ${p.rating}</div><div class="price-row"><strong>${money(p.price)}</strong><button class="small-btn" onclick="addCart(${p.id})">Add to Cart</button></div><a class="details" href="product.html?id=${p.id}">View details →</a></div></article>`}
function addCart(id){let c=getCart(),i=c.find(x=>x.id==id);i?i.qty++:c.push({id,qty:1});setCart(c);alert("Added to cart!")}
function toggleWish(id){let w=getWish(),i=w.indexOf(id);i>=0?w.splice(i,1):w.push(id);setWish(w);if($("wishlistPage"))renderWishlist();if($("shopProducts"))renderShop();if($("featured"))renderFeatured()}
function renderFeatured(){if($("featured"))$("featured").innerHTML=products.slice(0,4).map(card).join("")}
function renderShop(){if(!$("shopProducts"))return;let q=($("search")?.value||"").toLowerCase(),cat=$("category")?.value||"",sort=$("sort")?.value||"default";let a=products.filter(p=>(!q||(p.name+" "+p.category+" "+p.ingredients).toLowerCase().includes(q))&&(!cat||p.category==cat));if(sort=="low")a.sort((x,y)=>x.price-y.price);if(sort=="high")a.sort((x,y)=>y.price-x.price);if(sort=="rating")a.sort((x,y)=>y.rating-x.rating);$("shopProducts").innerHTML=a.length?a.map(card).join(""):"<div class='empty full'>No teas found.</div>";}
function renderProduct(){let id=new URLSearchParams(location.search).get("id"),p=products.find(x=>x.id==id)||products[0];$("productPage").innerHTML=`<div class="product-detail"><div class="detail-art">${p.emoji}</div><div><span class="tag">${p.category}</span><h1>${p.name}</h1><div class="rating">★ ${p.rating} / 5</div><h2>${money(p.price)}</h2><p>${p.desc}</p><hr><h3>Ingredients</h3><p>${p.ingredients}</p><h3>How to prepare</h3><p>Add 1–2 teaspoons to hot water and steep for 4–5 minutes. Adjust to taste.</p><div class="qty"><button onclick="changeDetailQty(-1)">−</button><span id="detailQty">1</span><button onclick="changeDetailQty(1)">+</button></div><button class="btn" onclick="addDetailCart(${p.id})">Add to Cart</button> <button class="btn outline" onclick="toggleWish(${p.id})">♡ Wishlist</button></div></div><section class="reviews"><h2>Customer Reviews</h2><div class="review">★★★★★ <b>Beautiful flavour</b><p>A lovely herbal blend for everyday tea time.</p></div></section>`}
function changeDetailQty(n){let e=$("detailQty"),v=Math.max(1,+e.textContent+n);e.textContent=v}
function addDetailCart(id){let q=+$("detailQty").textContent,c=getCart(),i=c.find(x=>x.id==id);i?i.qty+=q:c.push({id,qty:q});setCart(c);location.href="cart.html"}
function renderCart(){let c=getCart();if(!$("cartPage"))return;if(!c.length){$("cartPage").innerHTML="<div class='empty'><h2>Your cart is empty 🌿</h2><a class='btn' href='shop.html'>Shop Teas</a></div>";return}let subtotal=0;let rows=c.map(x=>{let p=products.find(p=>p.id==x.id),t=p.price*x.qty;subtotal+=t;return `<div class="cart-row"><div class="cart-art">${p.emoji}</div><div><h3>${p.name}</h3><p>${money(p.price)}</p></div><div class="qty"><button onclick="changeCart(${p.id},-1)">−</button><span>${x.qty}</span><button onclick="changeCart(${p.id},1)">+</button></div><strong>${money(t)}</strong><button class="remove" onclick="removeCart(${p.id})">×</button></div>`}).join("");let delivery=subtotal>=999?0:60; $("cartPage").innerHTML=`<div class="cart-layout"><div>${rows}</div><div class="summary-card"><h2>Order Summary</h2><p>Subtotal <b>${money(subtotal)}</b></p><p>Delivery <b>${delivery?money(delivery):"FREE"}</b></p><hr><h3>Total <b>${money(subtotal+delivery)}</b></h3><a class="btn fullbtn" href="checkout.html">Proceed to Checkout</a></div></div>`}
function changeCart(id,n){let c=getCart(),i=c.find(x=>x.id==id);if(i){i.qty+=n;if(i.qty<1)c=c.filter(x=>x.id!=id)}setCart(c);renderCart()}
function removeCart(id){setCart(getCart().filter(x=>x.id!=id));renderCart()}
function renderWishlist(){let w=getWish();$("wishlistPage").innerHTML=w.length?products.filter(p=>w.includes(p.id)).map(card).join(""):"<div class='empty full'><h2>No saved teas yet ♡</h2><a class='btn' href='shop.html'>Explore Teas</a></div>"}
function total(){return getCart().reduce((s,x)=>{let p=products.find(p=>p.id==x.id);return s+p.price*x.qty},0)}
function renderCheckout(){if(!$("checkoutSummary"))return;let t=total(),d=t>=999?0:60;$("checkoutSummary").innerHTML=`<h2>Order Summary</h2>${getCart().map(x=>{let p=products.find(p=>p.id==x.id);return `<p>${p.name} × ${x.qty}<b>${money(p.price*x.qty)}</b></p>`}).join("")}<hr><p>Delivery <b>${d?money(d):"FREE"}</b></p><h2>Total <b>${money(t+d)}</b></h2>`}
function saveAddress(e){e.preventDefault();let a={name:$("name").value,phone:$("phone").value,email:$("email").value,pin:$("pin").value,address:$("address").value,city:$("city").value,state:$("state").value,landmark:$("landmark").value};localStorage.setItem("ay_address",JSON.stringify(a));location.href="payment.html"}
function renderPayment(){let t=total(),d=t>=999?0:60;if(!$("paymentSummary"))return;$("paymentSummary").innerHTML=`<h2>Payable Amount</h2><p>Items <b>${money(t)}</b></p><p>Delivery <b>${d?money(d):"FREE"}</b></p><hr><h2>Total <b>${money(t+d)}</b></h2>`}
function payTab(type){let b=$("payBox");if(type=="upi")b.innerHTML=`<h2>Pay with UPI</h2><p>Enter your UPI ID</p><input id="upi" placeholder="example@upi"><button class="btn" onclick="placeOrder('UPI')">Pay Now</button>`;if(type=="card")b.innerHTML=`<h2>Card Payment</h2><input id="card" maxlength="19" placeholder="Card Number"><div class="form-grid"><input placeholder="MM/YY"><input placeholder="CVV" maxlength="3"></div><input placeholder="Cardholder Name"><button class="btn" onclick="placeOrder('Card')">Pay Now</button>`;if(type=="cod")b.innerHTML=`<h2>Cash on Delivery</h2><p>Pay when your order arrives.</p><button class="btn" onclick="placeOrder('Cash on Delivery')">Place Order</button>`}
function placeOrder(method){if(!getCart().length){location.href="shop.html";return}let id="AYU"+Date.now().toString().slice(-8),t=total(),d=t>=999?0:60,orders=JSON.parse(localStorage.getItem("ay_orders")||"[]");orders.unshift({id,date:new Date().toLocaleDateString("en-IN"),total:t+d,method,status:"Confirmed",items:getCart(),address:JSON.parse(localStorage.getItem("ay_address")||"{}")});localStorage.setItem("ay_orders",JSON.stringify(orders));localStorage.removeItem("ay_cart");localStorage.setItem("ay_last_order",id);location.href="success.html"}
function renderSuccess(){let id=localStorage.getItem("ay_last_order")||"AYU-DEMO";$("orderMessage").textContent=`Your order ${id} has been confirmed. You can view its status from My Orders.`}
function renderOrders(){let o=JSON.parse(localStorage.getItem("ay_orders")||"[]");$("ordersPage").innerHTML=o.length?o.map(x=>`<div class="order-card"><div><span class="tag">${x.status}</span><h3>${x.id}</h3><p>${x.date} • ${x.method}</p></div><strong>${money(x.total)}</strong><div class="order-track"><span>✓ Placed</span><span>✓ Confirmed</span><span>○ Packed</span><span>○ Shipped</span><span>○ Delivered</span></div></div>`).join(""):"<div class='empty'><h2>No orders yet.</h2><a class='btn' href='shop.html'>Start Shopping</a></div>"}
function renderProfile(){let u=JSON.parse(localStorage.getItem("ay_user")||"null");$("profilePage").innerHTML=u?`<div class="form-card"><h2>${u.name}</h2><p>${u.email}</p><p>${u.phone}</p><button class="btn" onclick="logout()">Logout</button></div>`:`<div class="empty"><h2>Please login to view your profile.</h2><a class="btn" href="login.html">Login</a></div>`}
function registerUser(e){e.preventDefault();let u={name:$("regName").value,email:$("regEmail").value,phone:$("regPhone").value,password:$("regPassword").value};localStorage.setItem("ay_user",JSON.stringify(u));alert("Account created successfully!");location.href="profile.html"}
function loginUser(e){e.preventDefault();let u=JSON.parse(localStorage.getItem("ay_user")||"null");let email=$("loginEmail").value;if(!u||u.email!=email){alert("Demo account not found. Please register first.");return}localStorage.setItem("ay_logged","1");location.href="profile.html"}
function logout(){localStorage.removeItem("ay_logged");location.href="index.html"}
function subscribe(e){e.preventDefault();alert("Thank you for subscribing to Ayushtha!")}
function contactSubmit(e){e.preventDefault();alert("Thank you! Your message has been received.");e.target.reset()}
nav();foot();renderFeatured();